library_path: ./library
includes:
    - prompts/claude
    - scripts/hooks
    - templates/common
    - patterns/error-handling
overrides: {}
persona_bindings:
    analyst: analyst-feedback
    architect: architect-systems
    code-reviewer: strict-code-reviewer
    developer: developer-senior-golang
    devops-engineer: devops-engineer-kubernetes
    test-engineer: test-engineer-tdd
    workflow-coordinator: helix-workflow-enforcer
workflow_phase_personas:
    helix:
        design: product-manager-minimalist
        test: test-engineer-tdd
preferences:
    auto_apply_hooks: true
    backup_before_update: true
    check_updates: true
repository:
    branch: main
    path: .ddx/
    url: https://github.com/easel/ddx
subtree:
    auto_update: false
    contribution_branch: contributions
    enabled: true
variables:
    ai_model: claude-3-opus
    architecture_description: Standard layered architecture
    auth_choice: NextAuth.js
    build_command: make build
    config_directory: config
    database_choice: PostgreSQL
    format_command: make format
    key_components: Core business logic, API layer, data access
    key_patterns: Error handling, logging, testing
    lint_command: make lint
    main_directory: src
    project_description: A new project using DDx toolkit
    project_name: '{{PROJECT_NAME}}'
    tech_stack: To be determined
    test_command: make test
version: 1
