name: development
version: 1.0.0
description: Iterative software development workflow from concept to deployment
author: DDX Team
created: 2025-01-12
tags:
  - software-development
  - iterative
  - documentation-driven
  - ai-enhanced

phases:
  - id: define
    order: 1
    name: Product Definition
    description: Establish clear requirements and product vision
    exit_criteria:
      - PRD completed and reviewed
      - Success metrics defined
      - Stakeholder approval received
    estimated_duration: 1-2 weeks

  - id: design
    order: 2
    name: Technical Architecture
    description: Design system architecture and make technical decisions
    exit_criteria:
      - Architecture documented
      - Technology choices made
      - Design review completed
    estimated_duration: 1-2 weeks
    
  - id: implement
    order: 3
    name: Feature Implementation
    description: Build the solution according to specifications
    exit_criteria:
      - Features implemented
      - Code reviews completed
      - Unit tests passing
    estimated_duration: variable
    
  - id: test
    order: 4
    name: Quality Assurance
    description: Validate implementation meets requirements
    exit_criteria:
      - Test plan executed
      - Acceptance criteria met
      - Defects resolved or documented
    estimated_duration: 20-30% of implementation
    
  - id: release
    order: 5
    name: Deployment
    description: Deploy solution to production
    exit_criteria:
      - Successfully deployed
      - Monitoring in place
      - Users notified
    estimated_duration: 1-3 days
    
  - id: iterate
    order: 6
    name: Feedback and Iteration
    description: Gather feedback and plan improvements
    exit_criteria:
      - Feedback analyzed
      - Improvements identified
      - Next iteration planned
    estimated_duration: ongoing

variables:
  - name: project_name
    description: Name of the project
    prompt: What is your project name?
    required: true
    
  - name: project_type
    description: Type of project
    prompt: What type of project is this?
    options:
      - web-application
      - mobile-app
      - api-service
      - library
      - cli-tool
    required: true
    
  - name: team_size
    description: Size of development team
    prompt: How many developers on the team?
    type: number
    default: 1

automation:
  init_command: ddx workflow init development
  status_command: ddx workflow status development
  validate_command: ddx workflow validate development
  
  hooks:
    pre_phase:
      - validate_entry_criteria
      - prepare_environment
    post_phase:
      - validate_exit_criteria
      - update_status
      - notify_stakeholders
      
integrations:
  - type: git
    events:
      - phase_complete
    actions:
      - create_branch
      - tag_release
      
  - type: github
    events:
      - release_complete
    actions:
      - create_github_release
      - update_project_board

quality_gates:
  - phase: design
    gate: architecture_review
    required_approvers: 2
    
  - phase: implement
    gate: code_review
    required_coverage: 80
    
  - phase: test
    gate: test_completion
    required_pass_rate: 95
    
  - phase: release
    gate: deployment_approval
    required_approvers: 1

metrics:
  - id: cycle_time
    description: Time from define to release
    unit: days
    
  - id: defect_rate
    description: Defects found post-release
    unit: count
    
  - id: velocity
    description: Features delivered per iteration
    unit: count