name: cdp
version: 1.0.0
description: Clinical Development Protocol for rigorous software development
author: DDX Clinical Team
created: 2025-01-12
tags:
  - clinical-development
  - validation-driven
  - evidence-based
  - quality-assured

phases:
  - id: diagnose
    order: 1
    name: Patient Diagnosis
    description: Comprehensive problem analysis and requirements assessment
    exit_criteria:
      - Complete diagnostic documentation created and reviewed
      - Treatment success metrics clearly defined and measurable
      - All stakeholders have provided clinical input and approval
      - Technical feasibility confirmed by clinical team
      - Diagnostic confidence level sufficient for treatment planning
    validation_gates:
      - diagnostic_completeness_check
      - stakeholder_clinical_review
      - technical_feasibility_assessment
    estimated_duration: 1-2 weeks

  - id: prescribe
    order: 2
    name: Treatment Planning
    description: Design comprehensive treatment approach and technical architecture
    exit_criteria:
      - Comprehensive treatment plan documented with clinical protocols
      - All technology choices justified with evidence-based rationale
      - Clinical architecture review completed by senior practitioners
      - Treatment risks assessed with mitigation strategies documented
      - Implementation approach validated and approved
    validation_gates:
      - treatment_plan_review
      - clinical_architecture_assessment
      - risk_mitigation_validation
      - senior_practitioner_approval
    estimated_duration: 1-2 weeks
    
  - id: treat
    order: 3
    name: Treatment Implementation
    description: Execute treatment plan with clinical precision and documentation
    exit_criteria:
      - All prescribed treatments implemented according to specifications
      - Clinical peer reviews (code reviews) completed and documented
      - Unit-level validation tests written and passing
      - Treatment implementation records comprehensive and current
      - Clinical quality standards met and verified
    validation_gates:
      - implementation_compliance_check
      - clinical_peer_review
      - treatment_quality_assessment
      - unit_validation_verification
    estimated_duration: variable based on treatment complexity
    
  - id: monitor
    order: 4
    name: Patient Monitoring
    description: Comprehensive validation and testing of treatment effectiveness
    exit_criteria:
      - Comprehensive monitoring plan executed successfully
      - All critical and high-severity adverse events resolved
      - Clinical performance and safety requirements validated
      - Patient acceptance testing completed successfully
      - Treatment effectiveness demonstrated through validation
    validation_gates:
      - monitoring_plan_execution
      - adverse_event_resolution
      - safety_validation
      - clinical_acceptance_testing
      - effectiveness_assessment
    estimated_duration: 20-30% of treatment duration
    
  - id: release
    order: 5
    name: Clinical Deployment
    description: Deploy validated treatment to production care environment
    exit_criteria:
      - Treatment successfully deployed to production environment
      - All clinical monitoring and alerting systems operational
      - Care team notified and documentation distributed
      - Post-deployment validation completed successfully
      - Patient handoff documentation completed
    validation_gates:
      - deployment_validation
      - monitoring_system_check
      - clinical_documentation_review
      - production_readiness_assessment
    estimated_duration: 1-3 days
    
  - id: follow-up
    order: 6
    name: Continuing Care
    description: Long-term monitoring and continuous improvement
    exit_criteria:
      - Patient outcomes analyzed and documented
      - Improvement opportunities identified and prioritized
      - Lessons learned captured for protocol improvement
      - Next treatment cycle planned if needed
    validation_gates:
      - outcome_analysis
      - improvement_identification
      - protocol_refinement
    estimated_duration: ongoing

variables:
  - name: patient_name
    description: Project/system name (the "patient")
    prompt: What is the name of your patient (project)?
    required: true
    
  - name: condition_severity
    description: Criticality level of the system
    prompt: What is the severity level of the condition?
    options:
      - critical
      - high
      - moderate
      - low
    required: true
    
  - name: care_team_size
    description: Size of development team
    prompt: How many practitioners on the care team?
    type: number
    default: 1
    
  - name: regulatory_requirements
    description: Compliance requirements
    prompt: Are there regulatory requirements?
    type: boolean
    default: false

automation:
  init_command: ddx workflow init cdp
  status_command: ddx workflow status cdp
  validate_command: ddx workflow validate cdp
  
  hooks:
    pre_phase:
      - validate_clinical_entry_criteria
      - prepare_clinical_environment
      - verify_compliance_requirements
    post_phase:
      - validate_clinical_exit_criteria
      - update_patient_record
      - generate_clinical_reports
      - notify_care_team
      
integrations:
  - type: git
    events:
      - phase_complete
    actions:
      - create_clinical_branch
      - tag_clinical_release
      
  - type: github
    events:
      - release_complete
    actions:
      - create_github_release
      - update_clinical_board
      
  - type: compliance
    events:
      - validation_gate_passed
    actions:
      - log_compliance_event
      - generate_audit_trail

quality_gates:
  - phase: diagnose
    gate: diagnostic_review
    required_approvers: 2
    clinical_level: senior
    
  - phase: prescribe
    gate: treatment_plan_review
    required_approvers: 3
    clinical_level: lead
    
  - phase: treat
    gate: implementation_review
    required_coverage: 90
    peer_reviews_required: 2
    
  - phase: monitor
    gate: clinical_validation
    required_pass_rate: 98
    adverse_event_tolerance: 0
    
  - phase: release
    gate: deployment_approval
    required_approvers: 2
    clinical_level: senior

metrics:
  - id: treatment_cycle_time
    description: Time from diagnosis to deployment
    unit: days
    
  - id: adverse_event_rate
    description: Issues found during monitoring
    unit: count
    severity_weighted: true
    
  - id: clinical_effectiveness
    description: Success rate of treatments
    unit: percentage
    
  - id: patient_satisfaction
    description: Stakeholder satisfaction score
    unit: score
    scale: 1-10