name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

# Minimal permissions by default
permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  # Main CI job using lefthook
  ci:
    name: CI Validation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Need full history for some checks
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        cache-dependency-path: cli/go.sum

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: v2.5.0
        working-directory: cli
        skip-cache: false

    - name: Install lefthook
      run: |
        # Install using Go for better reliability in CI
        go install github.com/evilmartians/lefthook@latest
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

    - name: Build CLI binary
      run: |
        cd cli
        make build

    - name: Run CI validation
      run: lefthook run ci
      env:
        LEFTHOOK_QUIET: meta,execution
        DDX_TEST_LIBRARY_PATH: ${{ github.workspace }}/.test-library

  # Separate build job for matrix builds
  build:
    name: Build
    needs: ci
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [amd64, arm64]
        exclude:
          - os: windows
            arch: arm64
    defaults:
      run:
        working-directory: cli
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        cache-dependency-path: cli/go.sum
    
    - name: Build binary
      run: |
        GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} \
          go build -v -o ../bin/ddx-${{ matrix.os }}-${{ matrix.arch }} .
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ddx-${{ matrix.os }}-${{ matrix.arch }}
        path: bin/ddx-${{ matrix.os }}-${{ matrix.arch }}
        retention-days: 7

  # Integration tests
  integration:
    name: Integration Tests
    needs: ci
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        cache-dependency-path: cli/go.sum
    
    - name: Install lefthook
      run: |
        # Install using Go for better reliability in CI
        go install github.com/evilmartians/lefthook@latest
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
    
    - name: Build CLI
      run: |
        cd cli
        go build -o ../bin/ddx
    
    - name: Setup DDx toolkit directory
      run: |
        # Create the DDx installation directory with library structure
        mkdir -p ~/.ddx/library
        cp -r library/* ~/.ddx/library/ || true
    
    - name: Test init command
      run: |
        mkdir -p test-project
        cd test-project
        ../bin/ddx init
        test -f .ddx.yml
    
    - name: Test list command
      run: |
        cd test-project
        ../bin/ddx list
    
    - name: Test pre-commit hooks
      run: |
        cd test-project
        git init
        lefthook install
        echo "test" > test.txt
        git add test.txt
        git commit -m "Test commit" || true