name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'README.md'
      - '.github/workflows/docs.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'README.md'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Pages
      uses: actions/configure-pages@v3
      
    - name: Create docs site
      run: |
        mkdir -p _site
        
        # Copy main README as index
        cp README.md _site/index.md
        
        # Copy docs directory
        cp -r docs/* _site/ 2>/dev/null || true
        
        # Create a simple HTML wrapper
        cat > _site/index.html << 'EOF'
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>DDx - Document-Driven Development eXperience</title>
            <style>
                body { 
                    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif;
                    max-width: 900px; 
                    margin: 0 auto; 
                    padding: 2rem;
                    line-height: 1.6;
                    color: #333;
                }
                code { 
                    background: #f6f8fa; 
                    padding: 0.2em 0.4em; 
                    border-radius: 3px;
                    font-size: 0.9em;
                }
                pre { 
                    background: #f6f8fa; 
                    padding: 1rem; 
                    border-radius: 6px; 
                    overflow-x: auto;
                }
                pre code { 
                    background: none; 
                    padding: 0; 
                }
                h1, h2, h3 { 
                    color: #0969da; 
                }
                .banner {
                    text-align: center;
                    padding: 2rem 0;
                    margin-bottom: 2rem;
                    border-bottom: 1px solid #e1e4e8;
                }
                .install-command {
                    background: #161b22;
                    color: #f0f6fc;
                    padding: 1rem;
                    border-radius: 6px;
                    font-family: 'SFMono-Regular', Consolas, 'Liberation Mono', Menlo, monospace;
                    margin: 1rem 0;
                    overflow-x: auto;
                }
                .nav {
                    background: #f6f8fa;
                    padding: 1rem;
                    border-radius: 6px;
                    margin-bottom: 2rem;
                }
                .nav a {
                    margin-right: 1rem;
                    text-decoration: none;
                    color: #0969da;
                }
                .nav a:hover {
                    text-decoration: underline;
                }
            </style>
        </head>
        <body>
            <div class="banner">
                <h1>🏥 DDx - Document-Driven Development eXperience</h1>
                <p>Like medical differential diagnosis, but for your development workflow</p>
                <div class="install-command">
                    curl -fsSL https://raw.githubusercontent.com/easel/ddx/main/install.sh | bash
                </div>
            </div>
            
            <div class="nav">
                <strong>📚 Documentation:</strong>
                <a href="#quick-start">Quick Start</a>
                <a href="getting-started.html">Getting Started</a>
                <a href="https://github.com/easel/ddx">GitHub</a>
                <a href="https://github.com/easel/ddx/releases">Releases</a>
            </div>
            
            <div id="content">
                <!-- Content will be injected here -->
            </div>
            
            <script>
                // Convert markdown to basic HTML (simplified)
                fetch('index.md')
                    .then(response => response.text())
                    .then(markdown => {
                        // Basic markdown to HTML conversion
                        let html = markdown
                            .replace(/^# (.*$)/gm, '<h1>$1</h1>')
                            .replace(/^## (.*$)/gm, '<h2>$1</h2>')
                            .replace(/^### (.*$)/gm, '<h3>$1</h3>')
                            .replace(/\*\*(.*)\*\*/g, '<strong>$1</strong>')
                            .replace(/\*(.*)\*/g, '<em>$1</em>')
                            .replace(/`(.*?)`/g, '<code>$1</code>')
                            .replace(/```([^`]*)```/g, '<pre><code>$1</code></pre>')
                            .replace(/\n/g, '<br>');
                        
                        document.getElementById('content').innerHTML = html;
                    })
                    .catch(() => {
                        document.getElementById('content').innerHTML = 
                            '<p>📖 Please visit the <a href="https://github.com/easel/ddx">GitHub repository</a> for full documentation.</p>';
                    });
            </script>
        </body>
        </html>
        EOF
        
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: ./_site

  deploy-docs:
    name: Deploy Documentation
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-docs
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2

  validate-docs:
    name: Validate Documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Check markdown links
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        config-file: '.github/markdown-link-check-config.json'
        
    - name: Check spelling
      uses: streetsidesoftware/cspell-action@v7
      with:
        files: |
          README.md
          docs/**/*.md
        config: '.github/cspell.json'